export enum MessageCode {
    SET_MENU_TYPE_NAVIGATION = 1,
    SET_MENU_TYPE_USER = 2,
    UPDATE_MY_PRODUCTS_LIST = 3,
    UPDATE_MY_CARDS_LIST = 4,
    UPDATE_MY_ADDRESS_LIST = 5,
    UPDATE_MY_PROMOTION_LIST = 6
}